title: Workshop on Online Abuse and Harms
logo: /assets/img/logo_woah.png
description: The 8th Workshop on Online Abuse and Harms (WOAH) on June 20/21 at NAACL 2024.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github: false
